
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_in]
set_property PACKAGE_PIN Y6 [get_ports rst_in]
set_property PACKAGE_PIN Y7 [get_ports clk_in]

set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_N[5]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_N[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_N[1]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_N[2]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_N[3]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_N[4]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_N[6]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_P[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_P[1]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_P[2]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_P[3]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_P[4]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_P[5]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataA_in_P[6]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports adc_clkP_out_P]
set_property PACKAGE_PIN K17 [get_ports adc_clkP_out_P]


set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_N[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_N[1]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_N[2]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_N[3]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_N[4]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_N[5]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_N[6]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_P[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_P[1]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_P[2]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_P[3]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_P[4]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_P[5]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {adc_dataB_in_P[6]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports adc_clkMout_in_N]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports adc_clkPout_in_P]
set_property IOSTANDARD LVCMOS18 [get_ports adc_ctrl1_out]
set_property IOSTANDARD LVCMOS18 [get_ports adc_ctrl2_out]
set_property IOSTANDARD LVCMOS18 [get_ports adc_ctrl3_out]
set_property IOSTANDARD LVCMOS18 [get_ports adc_reset_out]
set_property IOSTANDARD LVCMOS18 [get_ports adc_sclk_out]
set_property IOSTANDARD LVCMOS18 [get_ports adc_sdata_out]
set_property IOSTANDARD LVCMOS18 [get_ports adc_sdout_in]
set_property IOSTANDARD LVCMOS18 [get_ports adc_sen_out]

set_property PACKAGE_PIN H16 [get_ports adc_clkPout_in_P]
set_property PACKAGE_PIN M14 [get_ports adc_ctrl1_out]
set_property PACKAGE_PIN G18 [get_ports adc_ctrl2_out]
set_property PACKAGE_PIN H15 [get_ports adc_ctrl3_out]
set_property PACKAGE_PIN G17 [get_ports adc_reset_out]
set_property PACKAGE_PIN D20 [get_ports adc_sclk_out]
set_property PACKAGE_PIN F16 [get_ports adc_sen_out]
set_property PACKAGE_PIN K14 [get_ports {adc_dataA_in_P[6]}]
set_property PACKAGE_PIN L14 [get_ports {adc_dataA_in_P[5]}]
set_property PACKAGE_PIN L16 [get_ports {adc_dataA_in_P[4]}]
set_property PACKAGE_PIN M17 [get_ports {adc_dataA_in_P[3]}]
set_property PACKAGE_PIN M19 [get_ports {adc_dataA_in_P[2]}]
set_property PACKAGE_PIN L19 [get_ports {adc_dataA_in_P[1]}]
set_property PACKAGE_PIN N15 [get_ports {adc_dataA_in_P[0]}]
set_property PACKAGE_PIN E17 [get_ports {adc_dataB_in_P[6]}]
set_property PACKAGE_PIN E18 [get_ports {adc_dataB_in_P[5]}]
set_property PACKAGE_PIN C20 [get_ports {adc_dataB_in_P[3]}]
set_property PACKAGE_PIN B19 [get_ports {adc_dataB_in_P[4]}]
set_property PACKAGE_PIN F19 [get_ports {adc_dataB_in_P[2]}]
set_property PACKAGE_PIN G19 [get_ports {adc_dataB_in_P[1]}]
set_property PACKAGE_PIN K19 [get_ports {adc_dataB_in_P[0]}]
set_property PACKAGE_PIN H18 [get_ports adc_sdata_out]
set_property PACKAGE_PIN J18 [get_ports adc_sdout_in]



# test port
set_property IOSTANDARD LVCMOS33 [get_ports led_on]
set_property IOSTANDARD LVCMOS33 [get_ports SW3]
set_property IOSTANDARD LVCMOS33 [get_ports TX]
set_property IOSTANDARD LVCMOS33 [get_ports RX]


set_property PACKAGE_PIN R19 [get_ports led_on]
set_property PACKAGE_PIN W6 [get_ports SW3]
set_property PACKAGE_PIN V10 [get_ports TX]
set_property PACKAGE_PIN V11 [get_ports RX]







create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_test/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 14 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {m_axis_dout_tdata_amp0_debug[0]} {m_axis_dout_tdata_amp0_debug[1]} {m_axis_dout_tdata_amp0_debug[2]} {m_axis_dout_tdata_amp0_debug[3]} {m_axis_dout_tdata_amp0_debug[4]} {m_axis_dout_tdata_amp0_debug[5]} {m_axis_dout_tdata_amp0_debug[6]} {m_axis_dout_tdata_amp0_debug[7]} {m_axis_dout_tdata_amp0_debug[8]} {m_axis_dout_tdata_amp0_debug[9]} {m_axis_dout_tdata_amp0_debug[10]} {m_axis_dout_tdata_amp0_debug[11]} {m_axis_dout_tdata_amp0_debug[12]} {m_axis_dout_tdata_amp0_debug[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 14 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {m_axis_dout_tdata_amp1_debug[0]} {m_axis_dout_tdata_amp1_debug[1]} {m_axis_dout_tdata_amp1_debug[2]} {m_axis_dout_tdata_amp1_debug[3]} {m_axis_dout_tdata_amp1_debug[4]} {m_axis_dout_tdata_amp1_debug[5]} {m_axis_dout_tdata_amp1_debug[6]} {m_axis_dout_tdata_amp1_debug[7]} {m_axis_dout_tdata_amp1_debug[8]} {m_axis_dout_tdata_amp1_debug[9]} {m_axis_dout_tdata_amp1_debug[10]} {m_axis_dout_tdata_amp1_debug[11]} {m_axis_dout_tdata_amp1_debug[12]} {m_axis_dout_tdata_amp1_debug[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 14 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {m_axis_dout_tdata_amp_debug[0]} {m_axis_dout_tdata_amp_debug[1]} {m_axis_dout_tdata_amp_debug[2]} {m_axis_dout_tdata_amp_debug[3]} {m_axis_dout_tdata_amp_debug[4]} {m_axis_dout_tdata_amp_debug[5]} {m_axis_dout_tdata_amp_debug[6]} {m_axis_dout_tdata_amp_debug[7]} {m_axis_dout_tdata_amp_debug[8]} {m_axis_dout_tdata_amp_debug[9]} {m_axis_dout_tdata_amp_debug[10]} {m_axis_dout_tdata_amp_debug[11]} {m_axis_dout_tdata_amp_debug[12]} {m_axis_dout_tdata_amp_debug[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 14 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {s_axis_tdata0[0]} {s_axis_tdata0[1]} {s_axis_tdata0[2]} {s_axis_tdata0[3]} {s_axis_tdata0[4]} {s_axis_tdata0[5]} {s_axis_tdata0[6]} {s_axis_tdata0[7]} {s_axis_tdata0[8]} {s_axis_tdata0[9]} {s_axis_tdata0[10]} {s_axis_tdata0[11]} {s_axis_tdata0[12]} {s_axis_tdata0[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 14 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {s_axis_tdata1[0]} {s_axis_tdata1[1]} {s_axis_tdata1[2]} {s_axis_tdata1[3]} {s_axis_tdata1[4]} {s_axis_tdata1[5]} {s_axis_tdata1[6]} {s_axis_tdata1[7]} {s_axis_tdata1[8]} {s_axis_tdata1[9]} {s_axis_tdata1[10]} {s_axis_tdata1[11]} {s_axis_tdata1[12]} {s_axis_tdata1[13]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
