function Hd = fir
%FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 08-Jul-2019 21:10:00

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 100;  % Sampling Frequency

Fpass = 0;               % Passband Frequency
Fstop = 5;               % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dsp.FIRFilter( ...
    'FullPrecisionOverride', false, ...
    'Numerator', b, ...
    'CoefficientsDataType', 'Custom', ...
    'CustomCoefficientsDataType', numerictype(true,16,20), ...
    'ProductDataType', 'Custom', ...
    'CustomProductDataType', numerictype(true,31,35), ...
    'AccumulatorDataType', 'Custom', ...
    'CustomAccumulatorDataType', numerictype(true,36,35), ...
    'OutputDataType', 'Custom', ...
    'CustomOutputDataType', numerictype(true,36,35), ...
    'RoundingMethod', 'Convergent');



% [EOF]
