function Hd = hpf
%HPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 09-Jul-2019 16:07:42

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 100;  % Sampling Frequency

Fstop = 0;               % Stopband Frequency
Fpass = 5;               % Passband Frequency
Dstop = 0.01;            % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop, Fpass]/(Fs/2), [0 1], [Dstop, Dpass]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dsp.FIRFilter( ...
    'Numerator', b, ...
    'CoefficientsDataType', 'Custom', ...
    'CustomCoefficientsDataType', numerictype(true,16,15));

% [EOF]
